services:
  backend:
    build: ./backend
    container_name: cutr-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - internal
  
  db:
    image: postgres:18.1
    container_name: cutr-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cutr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - internal

  redis:
    image: redis:8.6
    container_name: cutr-redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - internal
    restart: always

  adminer: 
    image: adminer:5.4.2
    container_name: cutr-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge